#!/usr/bin/env bash
# Generate cases.tsv as the cartesian product of the EDIT-ME lists below.
# Prints the row count and a measured-cost note before writing.
set -euo pipefail

# ===== EDIT ME =====
TF_A_LIST="0.500 0.600 0.700"
POLARITY_LIST="-1"
IOTA_TARGET_LIST="0.05"
CURRENT_LIMIT_LIST="150000"
MPOL_NTOR_LIST="6/6"          # mpol/ntor pairs, e.g. "6/6 8/8 6/8"
MAXITER=150
STEP_RADIUS=0.15
VOLUME_TARGET="-"             # "-" = fitted seed volume
# ===================

out=${1:-$(cd "$(dirname "$0")" && pwd)/cases.tsv}
rows=0
{
  echo "# Generated by make_cases.sh on $(date -Iseconds). Edit lists there, not here."
  echo "# Columns: TF_a  polarity  iota_target  current_limit_A  mpol  ntor  maxiter  step_radius  volume_target"
  for tf_a in ${TF_A_LIST}; do
    for pol in ${POLARITY_LIST}; do
      for iota in ${IOTA_TARGET_LIST}; do
        for limit in ${CURRENT_LIMIT_LIST}; do
          for pair in ${MPOL_NTOR_LIST}; do
            mpol=${pair%%/*}; ntor=${pair##*/}
            printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
              "${tf_a}" "${pol}" "${iota}" "${limit}" "${mpol}" "${ntor}" \
              "${MAXITER}" "${STEP_RADIUS}" "${VOLUME_TARGET}"
            rows=$((rows + 1))
          done
        done
      done
    done
  done
} > "${out}"
n=$(grep -vc '^#' "${out}")
echo "wrote ${n} case(s) to ${out}"
echo "cost note: ~3 min/case measured at TF_a=0.4, mpol=ntor=6 on a 32-core node;"
echo "other orders are UNMEASURED — the first run at a new order is the measurement."
